### PR TITLE
chore: update dependencies and tests

### PR DESCRIPTION
**Pull request by azdanov**
Update dependencies to the latest version and fix jest config to ignore fixtures with snapshots.

### CODE REVIEW

**Comment by jorgegonzalez** [comment]
Why is this failing in CI?

**Comment by azdanov** [comment]
`error Received malformed response from registry for undefined. The registry may be down.`

Some issues with yarn and circleci.

**Comment by jorgegonzalez** [comment]
Running it again

**Comment by azdanov** [comment]
🤷‍♂️

**Pull request merged**
